import Head from 'next/head'
import { ThemeProvider, createTheme, responsiveFontSizes} from "@mui/material/styles"
import { useDarkMode } from '../../provider/DarkMode'
import { useForm } from '../../provider/Form'
import { useEffect } from 'react'


export default function Layout({children}){

  const { darkMode } = useDarkMode()

  let theme = createTheme({
    
    palette: {
      ...(darkMode
        ? {
          mode: "dark",
          }
        : {
          mode: "light",
        }
      ),
    },

    typography: {
      h1: {
        fontWeight: 400
      },
      h2: {
        fontWeight: 500,
        fontSize: "36px",
        color: "rgba(0,0,0,0.97)"
      },
      h3: {
        fontWeight: 400,
        fontSize: "28px",
        color: "rgba(0,0,0,0.97)"
      },
    }

  })

  // if(respostas.cor === "blue"){
  //   theme.palette.primary = {
  //     main: "#1976D2",
  //     light: "#42A5F5",
  //     dark: "#1565C0",
  //     contrastText: "#fff"
  //   }
  // }

  // else if(respostas.cor === "red"){
  //   theme.palette.primary = {
  //     main: "#f44336",
  //     light: "#f6685e",
  //     dark: "#aa2e25",
  //     contrastText: "#fff"
  //   }
  // }
  // else if(respostas.cor === "green"){
  //   theme.palette.primary = {
  //     main: "#4caf50",
  //     light: "#6fbf73",
  //     dark: "#357a38",
  //     contrastText: "#fff"
  //   }
  // }

  return(
    <ThemeProvider theme={theme} >
    <Head>
      <title>Data Science</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;300;400;500;700&family=Montserrat:wght@100;300;400;500;700&family=Nunito:wght@300;400;500;600;700;800&family=Poppins:wght@100;300;400;500;700&family=Roboto:wght@100;300;400;500;700&family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet"></link>
    </Head>
      {children}
    </ThemeProvider>
  )

}