import Head from 'next/head'
import { ThemeProvider, createTheme, responsiveFontSizes} from "@mui/material/styles"
import { useDarkMode } from '../../provider/DarkMode'
import { useForm } from '../../provider/Form'
import { useEffect } from 'react'


export default function Layout({children}){

  const { darkMode } = useDarkMode()

  let theme = createTheme({
    
    palette: {
      ...(darkMode
        ? {
          mode: "dark",
          primary: {
            main:  "#323232",
            light: "#323232",
            dark:  "#323232",
          },
          text: {
            primary: "#DEDEDE"
          },
          background: {
            paper: "#121212"
          },
          }
        : {
          mode: "light",
        }
      ),
    },

  })

  theme.typography = {
    h1: {
      fontWeight: 400
    },
    h2: {
      fontWeight: 500,
      fontSize: "36px",
      color: theme.palette.text.primary
    },
    h3: {
      fontWeight: 400,
      fontSize: "28px",
      color: theme.palette.text.primary
    },
    h5: {
      fontWeight: 400,
      fontSize: "1.125rem",
    },
    h6: {
      fontWeight: 400,
      fontSize: "1.125rem",
      color: theme.palette.text.primary   
    }
  }

  theme.components = {
    MuiButton: {
      variants: [
        {
          props: { variants: "initial" },
          style: {
            color: theme.palette.text.primary,
            border: "1px solid black"
          }
        }
      ]
    }
  }

  return(
    <ThemeProvider theme={theme} >
    <Head>
      <title>Data Science</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;300;400;500;700&family=Montserrat:wght@100;300;400;500;700&family=Nunito:wght@300;400;500;600;700;800&family=Poppins:wght@100;300;400;500;700&family=Roboto:wght@100;300;400;500;700&family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet"></link>
    </Head>
      {children}
    </ThemeProvider>
  )

}